STORES = [
    {"domain": "beskarforge.com.au", "url": "https://beskarforge.com.au"},
    {"domain": "blacklistcards.com", "url": "https://blacklistcards.com"},
    {"domain": "boomerangcollectables.com", "url": "https://boomerangcollectables.com"},
    {"domain": "brutaldeluxe.com.au", "url": "https://brutaldeluxe.com.au"},
    {"domain": "cardbot.com.au", "url": "https://cardbot.com.au"},
    {"domain": "cardhouse.com.au", "url": "https://cardhouse.com.au"},
    {"domain": "cardkonbini.com.au", "url": "https://cardkonbini.com.au"},
    {"domain": "cardtradersaustralia.com.au", "url": "https://cardtradersaustralia.com.au"},
    {"domain": "cherrycollectables.com.au", "url": "https://cherrycollectables.com.au"},
    {"domain": "collectableloot.com.au", "url": "https://collectableloot.com.au"},
    {"domain": "collectiblemadness.com.au", "url": "https://collectiblemadness.com.au"},
    {"domain": "collectors-space.shop", "url": "https://collectors-space.shop"},
    {"domain": "collectorsquest.com.au", "url": "https://collectorsquest.com.au"},
    {"domain": "collectorstreasure.com.au", "url": "https://collectorstreasure.com.au"},
    {"domain": "countlesscards.com", "url": "https://countlesscards.com"},
    {"domain": "crithit.com.au", "url": "https://crithit.com.au"},
    {"domain": "firstgames.com.au", "url": "https://firstgames.com.au"},
    {"domain": "flukeandbox.com", "url": "https://flukeandbox.com"},
    {"domain": "frenlybricks.store", "url": "https://frenlybricks.store"},
    {"domain": "fromthedeepgames.com.au", "url": "https://fromthedeepgames.com.au"},
    {"domain": "gameology.com.au", "url": "https://gameology.com.au"},
    {"domain": "gamers-village.com.au", "url": "https://gamers-village.com.au"},
    {"domain": "gamerscombined.com.au", "url": "https://gamerscombined.com.au"},
    {"domain": "gamesempire.com.au", "url": "https://gamesempire.com.au"},
    {"domain": "hrgames.au", "url": "https://hrgames.au"},
    {"domain": "iconsofsport.com.au", "url": "https://iconsofsport.com.au"},
    {"domain": "inngames.com.au", "url": "https://inngames.com.au"},
    {"domain": "irresistibleforce.com.au", "url": "https://irresistibleforce.com.au"},
    {"domain": "justcardstuff.com.au", "url": "https://justcardstuff.com.au"},
    {"domain": "kandkcreativetoys.com.au", "url": "https://kandkcreativetoys.com.au"},
    {"domain": "kawaiicollector.com.au", "url": "https://kawaiicollector.com.au"},
    {"domain": "kidnplay.au", "url": "https://kidnplay.au"},
    {"domain": "kingscomics.com", "url": "https://kingscomics.com"},
    {"domain": "kollecter.com.au", "url": "https://kollecter.com.au"},
    {"domain": "legendsandcollectables.com", "url": "https://legendsandcollectables.com"},
    {"domain": "leogames.com.au", "url": "https://leogames.com.au"},
    {"domain": "lightofcards.com.au", "url": "https://lightofcards.com.au"},
    {"domain": "lunacards.com.au", "url": "https://lunacards.com.au"},
    {"domain": "manamarket.com.au", "url": "https://manamarket.com.au"},
    {"domain": "mastercoins.com.au", "url": "https://mastercoins.com.au"},
    {"domain": "mayhemcollectables.com.au", "url": "https://mayhemcollectables.com.au"},
    {"domain": "mtgsinglesaustralia.com", "url": "https://mtgsinglesaustralia.com"},
    {"domain": "obsessiongaming.com.au", "url": "https://obsessiongaming.com.au"},
    {"domain": "omegagames.com.au", "url": "https://omegagames.com.au"},
    {"domain": "omnicollectables.com.au", "url": "https://omnicollectables.com.au"},
    {"domain": "onlinecoinsandcollectables.com.au", "url": "https://onlinecoinsandcollectables.com.au"},
    {"domain": "ozziecollectables.com", "url": "https://ozziecollectables.com"},
    {"domain": "ozziecollectables.com.au", "url": "https://ozziecollectables.com.au"},
    {"domain": "pacifictcgstore.com", "url": "https://pacifictcgstore.com"},
    {"domain": "packmancollectables.com.au", "url": "https://packmancollectables.com.au"},
    {"domain": "shop.goodgames.com.au", "url": "https://shop.goodgames.com.au"},
    {"domain": "shuffled.com.au", "url": "https://shuffled.com.au"},
    {"domain": "sjay2k.com", "url": "https://sjay2k.com"},
    {"domain": "spellroogaming.com.au", "url": "https://spellroogaming.com.au"},
    {"domain": "stmarys.dragons-lair.com.au", "url": "https://stmarys.dragons-lair.com.au"},
    {"domain": "stonemonkey.com.au", "url": "https://stonemonkey.com.au"},
    {"domain": "t3games.com.au", "url": "https://t3games.com.au"},
    {"domain": "tabernaclegames.com.au", "url": "https://tabernaclegames.com.au"},
    {"domain": "tabletopgames.com.au", "url": "https://tabletopgames.com.au"},
    {"domain": "tcg.goodgames.com.au", "url": "https://tcg.goodgames.com.au"},
    {"domain": "tcg.tabernaclegames.com.au", "url": "https://tcg.tabernaclegames.com.au"},
    {"domain": "tcgroupau.com.au", "url": "https://tcgroupau.com.au"},
    {"domain": "techzonegeelong.com", "url": "https://techzonegeelong.com"},
    {"domain": "tempestcollectables.com", "url": "https://tempestcollectables.com"},
    {"domain": "theadventurersguild.com.au", "url": "https://theadventurersguild.com.au"},
    {"domain": "thecardcave.com.au", "url": "https://thecardcave.com.au"},
    {"domain": "thecardhubaustralia.com.au", "url": "https://thecardhubaustralia.com.au"},
    {"domain": "thecardspot.com.au", "url": "https://thecardspot.com.au"},
    {"domain": "thecollectorsmith.com.au", "url": "https://thecollectorsmith.com.au"},
    {"domain": "thecombatcompany.com.au", "url": "https://thecombatcompany.com.au"},
    {"domain": "thefinalbosscollectables.com.au", "url": "https://thefinalbosscollectables.com.au"},
    {"domain": "thegameexperts.com.au", "url": "https://thegameexperts.com.au"},
    {"domain": "topdeckgames.com.au", "url": "https://topdeckgames.com.au"},
    {"domain": "topdeckgaming.com.au", "url": "https://topdeckgaming.com.au"},
    {"domain": "toyboxtales.com.au", "url": "https://toyboxtales.com.au"},
    {"domain": "toyworld.com.au", "url": "https://toyworld.com.au"},
    {"domain": "tradingcardmasters.com.au", "url": "https://tradingcardmasters.com.au"},
    {"domain": "trainertown.com.au", "url": "https://trainertown.com.au"},
    {"domain": "tridentcollectables.com.au", "url": "https://tridentcollectables.com.au"},
    {"domain": "trollaustralia.com.au", "url": "https://trollaustralia.com.au"},
    {"domain": "trollaustraliamelb.com.au", "url": "https://trollaustraliamelb.com.au"},
    {"domain": "unpluggedgames.com.au", "url": "https://unpluggedgames.com.au"},
    {"domain": "urbanempirecollectables.com", "url": "https://urbanempirecollectables.com"},
    {"domain": "vault-collectables.com", "url": "https://vault-collectables.com"},
    {"domain": "vaultgames.com.au", "url": "https://vaultgames.com.au"},
]
# --- Game detection keywords ---
# Matched against product title + product_type + tags (lowercased).
GAME_KEYWORDS = {
    "pokemon": ["pokemon", "pokémon"],
    "one_piece": ["one piece"],
    "mtg": ["magic the gathering", "magic: the gathering", "mtg"],
    "riftbound": ["riftbound"],
}

# --- Product line phrases per game ---
# ORDER MATTERS: more specific phrases must come before their shorter substrings,
# e.g. "booster box display case" before "booster box case" before "booster box",
# so we record the most precise match rather than the generic one.
PRODUCT_LINES = {
    "pokemon": [
        "pokemon center elite trainer box case",
        "pokemon center elite trainer box",
        "elite trainer box display case",
        "elite trainer box case",
        "elite trainer box",
        "booster box display case",
        "booster box case",
        "booster box",
        "premium collection case",
        "premium collection",
        "booster bundle display case",
        "booster bundle case",
        "booster bundle",
        "sleeved booster pack case",
    ],
    "one_piece": [
        "booster box display case",
        "booster box case",
        "booster box",
    ],
    "riftbound": [
        "booster box display case",
        "booster box case",
        "booster box",
    ],
    "mtg": [
        "collector box master case",
        "collector box case",
        "collector box",
    ],
}

# --- Discord webhook routing ---
# These must match the GitHub Secret names exactly (Settings -> Secrets and
# variables -> Actions). Rename here if your secret names differ.
WEBHOOK_ENV_VARS = {
    "pokemon": "DISCORD_WEBHOOK_POKEMON",
    "one_piece": "DISCORD_WEBHOOK_ONEPIECE",
    "mtg": "DISCORD_WEBHOOK_MTG",
    "riftbound": "DISCORD_WEBHOOK_RIFTBOUND",
}
